//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSerifsAndScribes_MP
{
    public partial class AnnouncementsDashboard
    {
        protected global::System.Web.UI.WebControls.Panel MessagePanel;
        protected global::System.Web.UI.WebControls.TextBox TitleTextBox;
        protected global::System.Web.UI.WebControls.TextBox BodyTextBox;
        protected global::System.Web.UI.WebControls.Button AddButton;
        protected global::System.Web.UI.WebControls.GridView AnnouncementsGrid;
    }
}