//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheSerifsAndScribes_MP
{
    public partial class Announcements
    {
        /// <summary>
        /// EmptyStatePanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel EmptyStatePanel;

        /// <summary>
        /// AnnouncementsRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater AnnouncementsRepeater;
    }
}